### ISSUE TITLE
Cannot establish connection after deployment

### ISSUE THREAD

**Issue by christianvictoria** [tiger2380/simple_sfu#3]
![image](https://user-images.githubusercontent.com/71063843/173387376-5821f087-aff5-4a80-8646-d04e42e7ae4d.png)

Hi there, I have this issue where everything works fine on local but after deploying the backend somehow it doesn't establish connection. Please see attached image file, you will see that on chrome://webrtc-internals it says ice candidate pair (not connected) but works perfectly fine on local. I also have my own TURN/STUN server from subscription, please kindly help me on this issue.

**Comment by tiger2380** [comment]
Hmmm. Did you test your TURN/STUN servers to make sure they are working correctly?
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by christianvictoria** [comment]
Yes, they are working. I've been using it for my peer 2 peer which can only
accomodate 3-5 participants so I want to switch to sfu and then this thing
happens.
